// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: financial.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    owner_user_id
) VALUES (
    $1
)
RETURNING id, owner_user_id, balance, created_at
`

func (q *Queries) CreateAccount(ctx context.Context, ownerUserID pgtype.UUID) (*Account, error) {
	row := q.db.QueryRow(ctx, createAccount, ownerUserID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Balance,
		&i.CreatedAt,
	)
	return &i, err
}

const createEscrowSettlement = `-- name: CreateEscrowSettlement :one
INSERT INTO escrow_settlements (
    order_id,
    seller_account_id,
    amount_to_release,
    status,
    release_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, order_id, seller_account_id, amount_to_release, status, release_at, released_at, created_at
`

func (q *Queries) CreateEscrowSettlement(ctx context.Context, orderID uuid.UUID, sellerAccountID uuid.UUID, amountToRelease string, status string, releaseAt pgtype.Timestamp) (*EscrowSettlement, error) {
	row := q.db.QueryRow(ctx, createEscrowSettlement,
		orderID,
		sellerAccountID,
		amountToRelease,
		status,
		releaseAt,
	)
	var i EscrowSettlement
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SellerAccountID,
		&i.AmountToRelease,
		&i.Status,
		&i.ReleaseAt,
		&i.ReleasedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getAccount = `-- name: GetAccount :one
SELECT id, owner_user_id, balance, created_at
FROM accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAccount(ctx context.Context, id uuid.UUID) (*Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Balance,
		&i.CreatedAt,
	)
	return &i, err
}

const createPrimaryOrder = `-- name: CreatePrimaryOrder :one
INSERT INTO orders (
    user_id,
    total_amount,
    convenience_fee,
    platform_type,
    status,
    event_date
) VALUES (
    $1, $2, $3, 'PRIMARY', 'pending', $4
)
RETURNING id, user_id, total_amount, status, created_at
`

type CreatePrimaryOrderRow struct {
	ID          uuid.UUID        `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	TotalAmount string           `json:"total_amount"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreatePrimaryOrder(ctx context.Context, userID pgtype.UUID, totalAmount string, convenienceFee string, eventDate time.Time) (*CreatePrimaryOrderRow, error) {
	row := q.db.QueryRow(ctx, createPrimaryOrder,
		userID,
		totalAmount,
		convenienceFee,
		eventDate,
	)
	var i CreatePrimaryOrderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const getPrimaryTicketTypeForUpdate = `-- name: GetPrimaryTicketTypeForUpdate :one
SELECT
    id,
    event_id,
    nome,
    price,
    total_quantity,
    available_quantity,
    is_half_price_eligible,
    max_half_price_quantity,
    sold_half_price_quantity,
    producer_account_id,
    event_date
FROM ticket_types
WHERE id = $1
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetPrimaryTicketTypeForUpdate(ctx context.Context, id uuid.UUID) (*TicketType, error) {
	row := q.db.QueryRow(ctx, getPrimaryTicketTypeForUpdate, id)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Nome,
		&i.Price,
		&i.TotalQuantity,
		&i.AvailableQuantity,
		&i.IsHalfPriceEligible,
		&i.MaxHalfPriceQuantity,
		&i.SoldHalfPriceQuantity,
		&i.ProducerAccountID,
		&i.EventDate,
	)
	return &i, err
}

const incrementHalfPriceCount = `-- name: IncrementHalfPriceCount :exec
UPDATE ticket_types
SET sold_half_price_quantity = sold_half_price_quantity + 1
WHERE id = $1
    AND is_half_price_eligible = TRUE
    AND sold_half_price_quantity < max_half_price_quantity
`

func (q *Queries) IncrementHalfPriceCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementHalfPriceCount, id)
	return err
}

const listAccountsByOwner = `-- name: ListAccountsByOwner :many
SELECT id, owner_user_id, balance, created_at
FROM accounts
WHERE owner_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAccountsByOwner(ctx context.Context, ownerUserID pgtype.UUID) ([]*Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Balance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaturedSettlements = `-- name: ListMaturedSettlements :many
SELECT id, order_id, seller_account_id, amount_to_release, status, release_at, released_at, created_at
FROM escrow_settlements
WHERE status = 'HELD'
    AND release_at <= $1
ORDER BY release_at ASC
`

func (q *Queries) ListMaturedSettlements(ctx context.Context, releaseAt pgtype.Timestamp) ([]*EscrowSettlement, error) {
	rows, err := q.db.Query(ctx, listMaturedSettlements, releaseAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*EscrowSettlement{}
	for rows.Next() {
		var i EscrowSettlement
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SellerAccountID,
			&i.AmountToRelease,
			&i.Status,
			&i.ReleaseAt,
			&i.ReleasedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = balance + $1
WHERE id = $2
`

func (q *Queries) UpdateAccountBalance(ctx context.Context, balance string, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, balance, iD)
	return err
}

const updateSettlementStatus = `-- name: UpdateSettlementStatus :exec
UPDATE escrow_settlements
SET status = $1,
    released_at = CASE WHEN $1 = 'RELEASED' THEN NOW() ELSE released_at END
WHERE id = $2
`

func (q *Queries) UpdateSettlementStatus(ctx context.Context, status string, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSettlementStatus, status, iD)
	return err
}
