// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID          uuid.UUID        `json:"id"`
	UserID      pgtype.UUID      `json:"user_id"`
	TotalAmount string           `json:"total_amount"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

type Ticket struct {
	ID           uuid.UUID   `json:"id"`
	TicketTypeID uuid.UUID   `json:"ticket_type_id"`
	OrderID      pgtype.UUID `json:"order_id"`
	SeatNumber   pgtype.Text `json:"seat_number"`
	Status       string      `json:"status"`
	QrCodeToken  pgtype.Text `json:"qr_code_token"`
}

type TicketReservation struct {
	ID         uuid.UUID        `json:"id"`
	TicketID   uuid.UUID        `json:"ticket_id"`
	UserID     uuid.UUID        `json:"user_id"`
	ReservedAt pgtype.Timestamp `json:"reserved_at"`
	ExpiresAt  pgtype.Timestamp `json:"expires_at"`
	Status     string           `json:"status"`
}

type TicketType struct {
	ID                uuid.UUID `json:"id"`
	EventID           uuid.UUID `json:"event_id"`
	Nome              string    `json:"nome"`
	Price             string    `json:"price"`
	TotalQuantity     int32     `json:"total_quantity"`
	AvailableQuantity int32     `json:"available_quantity"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	HashedPassword string             `json:"hashed_password"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}
