// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, total_amount, status, Created_at)
VALUES ($1, $2, 'pending', NOW())
RETURNING id, user_id, total_amount, status, created_at
`

// Cria o pedido inicialmente com o status 'pending' (o total_amount vira string no Go)
func (q *Queries) CreateOrder(ctx context.Context, userID pgtype.UUID, totalAmount string) (*Order, error) {
	row := q.db.QueryRow(ctx, createOrder, userID, totalAmount)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, user_id, total_amount, status, created_at FROM orders
WHERE id = $1 LIMIT 1
FOR UPDATE
`

// Trava o pedido para evitar que um webhook de pagamento processado duas vezes mude o status simultaneamente
func (q *Queries) GetOrderForUpdate(ctx context.Context, id uuid.UUID) (*Order, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TotalAmount,
		&i.Status,
		&i.CreatedAt,
	)
	return &i, err
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, total_amount, status, created_at FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
`

// Histórico de compras do cliente no app/site
func (q *Queries) ListOrdersByUser(ctx context.Context, userID pgtype.UUID) ([]*Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TotalAmount,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :exec
UPDATE orders
SET status = $1
WHERE id = $2
`

// Atualiza o status do pedido (paid, cancelled, refunded)
func (q *Queries) UpdateOrderStatus(ctx context.Context, status string, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateOrderStatus, status, iD)
	return err
}
