// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Vincula o ingresso ao pedido final e gera o token do QR Code (pós-pagamento)
	AttachTicketToOrder(ctx context.Context, iD uuid.UUID, orderID pgtype.UUID, qrCodeToken pgtype.Text) error
	// Trava e reserva o PRIMEIRO ingresso disponível do lote selecionado.
	// O SKIP LOCKED evita que duas requisições fiquem presas tentando pegar o mesmo ingresso.
	BookAvailableTicket(ctx context.Context, ticketTypeID uuid.UUID) (*Ticket, error)
	// Chamado se o usuário desistir explicitamente ou o pagamento falhar direto
	CancelReservation(ctx context.Context, id uuid.UUID) error
	// Chamado quando o gateway de pagamento confirma o sucesso da compra
	CompleteReservation(ctx context.Context, id uuid.UUID) error
	// Cria o pedido inicialmente com o status 'pending' (o total_amount vira string no Go)
	CreateOrder(ctx context.Context, userID pgtype.UUID, totalAmount string) (*Order, error)
	CreateReservation(ctx context.Context, ticketID uuid.UUID, userID uuid.UUID, expiresAt pgtype.Timestamp) (*TicketReservation, error)
	CreateUser(ctx context.Context, email string, hashedPassword string) (*CreateUserRow, error)
	// Atualiza em lote o status das reservas que passaram do tempo
	ExpirePastReservations(ctx context.Context) error
	// Trava o pedido para evitar que um webhook de pagamento processado duas vezes mude o status simultaneamente
	GetOrderForUpdate(ctx context.Context, id uuid.UUID) (*Order, error)
	GetReservation(ctx context.Context, id uuid.UUID) (*TicketReservation, error)
	GetReservationForUpdate(ctx context.Context, id uuid.UUID) (*TicketReservation, error)
	GetTicket(ctx context.Context, id uuid.UUID) (*Ticket, error)
	GetTicketType(ctx context.Context, id uuid.UUID) (*TicketType, error)
	// Trava o lote para atualizar a quantidade disponível com segurança financeira
	GetTicketTypeForUpdate(ctx context.Context, id uuid.UUID) (*TicketType, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	ListActiveReservationsByUser(ctx context.Context, userID uuid.UUID) ([]*TicketReservation, error)
	// Lista os ingressos livres para o usuário escolher na tela (sem travar o banco)
	ListAvailableTickets(ctx context.Context, ticketTypeID uuid.UUID) ([]*Ticket, error)
	// Usado pelo worker em Go para descobrir quem perdeu o prazo
	ListExpiredReservations(ctx context.Context) ([]*TicketReservation, error)
	// Histórico de compras do cliente no app/site
	ListOrdersByUser(ctx context.Context, userID pgtype.UUID) ([]*Order, error)
	// Lista todos os setores/lotes de um evento para mostrar na página de vendas
	ListTicketTypesByEvent(ctx context.Context, eventID uuid.UUID) ([]*TicketType, error)
	// Lista todos os ingressos de um pedido específico (para gerar os PDFs/QR Codes)
	ListTicketsByOrder(ctx context.Context, orderID pgtype.UUID) ([]*Ticket, error)
	// Devolve os ingressos ao estoque caso a reserva expire ou seja cancelada
	ReleaseTicketsStock(ctx context.Context, availableQuantity int32, iD uuid.UUID) error
	// Deduz a quantidade disponível quando uma reserva é criada
	ReserveTicketsStock(ctx context.Context, availableQuantity int32, iD uuid.UUID) error
	// Atualiza o status do pedido (paid, cancelled, refunded)
	UpdateOrderStatus(ctx context.Context, status string, iD uuid.UUID) error
	// Caso precise virar o lote ou alterar o valor (o preço vira string no Go)
	UpdateTicketTypePrice(ctx context.Context, price string, iD uuid.UUID) (*TicketType, error)
}

var _ Querier = (*Queries)(nil)
