// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachTicketToOrder = `-- name: AttachTicketToOrder :exec
UPDATE tickets
SET status = 'sold',
    order_id = $2,
    qr_code_token =$3
WHERE id = $1
`

// Vincula o ingresso ao pedido final e gera o token do QR Code (pós-pagamento)
func (q *Queries) AttachTicketToOrder(ctx context.Context, iD uuid.UUID, orderID pgtype.UUID, qrCodeToken pgtype.Text) error {
	_, err := q.db.Exec(ctx, attachTicketToOrder, iD, orderID, qrCodeToken)
	return err
}

const bookAvailableTicket = `-- name: BookAvailableTicket :one
UPDATE tickets
SET status = 'reserved'
WHERE id = (
    SELECT t.id
    FROM tickets t
    LEFT JOIN ticket_reservations tr ON t.id = tr.ticket_id
        AND tr.status = 'pending'
        AND tr.expires_at > NOW()
    WHERE t.status = 'available'
        AND t.ticket_type_id = $1
        AND tr.id IS NULL LIMIT 1
        FOR UPDATE SKIP LOCKED
)
RETURNING id, ticket_type_id, order_id, seat_number, status, qr_code_token
`

// Trava e reserva o PRIMEIRO ingresso disponível do lote selecionado.
// O SKIP LOCKED evita que duas requisições fiquem presas tentando pegar o mesmo ingresso.
func (q *Queries) BookAvailableTicket(ctx context.Context, ticketTypeID uuid.UUID) (*Ticket, error) {
	row := q.db.QueryRow(ctx, bookAvailableTicket, ticketTypeID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TicketTypeID,
		&i.OrderID,
		&i.SeatNumber,
		&i.Status,
		&i.QrCodeToken,
	)
	return &i, err
}

const getTicket = `-- name: GetTicket :one
SELECT id, ticket_type_id, order_id, seat_number, status, qr_code_token FROM tickets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTicket(ctx context.Context, id uuid.UUID) (*Ticket, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.TicketTypeID,
		&i.OrderID,
		&i.SeatNumber,
		&i.Status,
		&i.QrCodeToken,
	)
	return &i, err
}

const listAvailableTickets = `-- name: ListAvailableTickets :many
SELECT t.id, t.ticket_type_id, t.order_id, t.seat_number, t.status, t.qr_code_token FROM tickets t
LEFT JOIN ticket_reservations tr ON t.id = tr.ticket_id
    AND tr.status = 'pending'
    AND tr.expires_at > NOW()
WHERE t.status = 'available'
    AND t.ticket_type_id = $1
    AND tr.id IS NULL
`

// Lista os ingressos livres para o usuário escolher na tela (sem travar o banco)
func (q *Queries) ListAvailableTickets(ctx context.Context, ticketTypeID uuid.UUID) ([]*Ticket, error) {
	rows, err := q.db.Query(ctx, listAvailableTickets, ticketTypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TicketTypeID,
			&i.OrderID,
			&i.SeatNumber,
			&i.Status,
			&i.QrCodeToken,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsByOrder = `-- name: ListTicketsByOrder :many
SELECT id, ticket_type_id, order_id, seat_number, status, qr_code_token FROM tickets
WHERE order_id = $1
`

// Lista todos os ingressos de um pedido específico (para gerar os PDFs/QR Codes)
func (q *Queries) ListTicketsByOrder(ctx context.Context, orderID pgtype.UUID) ([]*Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Ticket{}
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.TicketTypeID,
			&i.OrderID,
			&i.SeatNumber,
			&i.Status,
			&i.QrCodeToken,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnTicketToAvailable = `-- name: ReturnTicketToAvailable :exec
UPDATE tickets
SET status = 'available',
    order_id = NULL,
    qr_code_token = NULL
WHERE id = $1
    AND status = 'reserved'
`

func (q *Queries) ReturnTicketToAvailable(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, returnTicketToAvailable, id)
	return err
}
