// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticket_reservations.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelReservation = `-- name: CancelReservation :exec
UPDATE ticket_reservations
SET status = 'expired'
WHERE id = $1
`

// Chamado se o usuário desistir explicitamente ou o pagamento falhar direto
func (q *Queries) CancelReservation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelReservation, id)
	return err
}

const completeReservation = `-- name: CompleteReservation :exec
UPDATE ticket_reservations
SET status = 'completed'
WHERE id = $1
`

// Chamado quando o gateway de pagamento confirma o sucesso da compra
func (q *Queries) CompleteReservation(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeReservation, id)
	return err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO ticket_reservations (
    ticket_id,
    user_id,
    reserved_at,
    expires_at,
    status
) VALUES (
    $1, $2, NOW(), $3, 'pending'
)
RETURNING id, ticket_id, user_id, reserved_at, expires_at, status
`

func (q *Queries) CreateReservation(ctx context.Context, ticketID uuid.UUID, userID uuid.UUID, expiresAt pgtype.Timestamp) (*TicketReservation, error) {
	row := q.db.QueryRow(ctx, createReservation, ticketID, userID, expiresAt)
	var i TicketReservation
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UserID,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.Status,
	)
	return &i, err
}

const expirePastReservations = `-- name: ExpirePastReservations :exec
UPDATE ticket_reservations
SET status = 'expired'
WHERE status = 'pending'
    AND expires_at < NOW()
`

// Atualiza em lote o status das reservas que passaram do tempo
func (q *Queries) ExpirePastReservations(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expirePastReservations)
	return err
}

const getReservation = `-- name: GetReservation :one
SELECT id, ticket_id, user_id, reserved_at, expires_at, status FROM ticket_reservations
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetReservation(ctx context.Context, id uuid.UUID) (*TicketReservation, error) {
	row := q.db.QueryRow(ctx, getReservation, id)
	var i TicketReservation
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UserID,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.Status,
	)
	return &i, err
}

const getReservationForUpdate = `-- name: GetReservationForUpdate :one
SELECT id, ticket_id, user_id, reserved_at, expires_at, status FROM ticket_reservations
WHERE id = $1 
LIMIT 1
FOR UPDATE
`

func (q *Queries) GetReservationForUpdate(ctx context.Context, id uuid.UUID) (*TicketReservation, error) {
	row := q.db.QueryRow(ctx, getReservationForUpdate, id)
	var i TicketReservation
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UserID,
		&i.ReservedAt,
		&i.ExpiresAt,
		&i.Status,
	)
	return &i, err
}

const listActiveReservationsByUser = `-- name: ListActiveReservationsByUser :many
SELECT id, ticket_id, user_id, reserved_at, expires_at, status FROM ticket_reservations
WHERE user_id = $1
    AND status = 'pending'
    AND expires_at > NOW()
ORDER BY reserved_at DESC
`

func (q *Queries) ListActiveReservationsByUser(ctx context.Context, userID uuid.UUID) ([]*TicketReservation, error) {
	rows, err := q.db.Query(ctx, listActiveReservationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*TicketReservation{}
	for rows.Next() {
		var i TicketReservation
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.UserID,
			&i.ReservedAt,
			&i.ExpiresAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredReservations = `-- name: ListExpiredReservations :many
SELECT id, ticket_id, user_id, reserved_at, expires_at, status FROM ticket_reservations
WHERE status = 'pending' 
  AND expires_at < NOW()
`

// Usado pelo worker em Go para descobrir quem perdeu o prazo
func (q *Queries) ListExpiredReservations(ctx context.Context) ([]*TicketReservation, error) {
	rows, err := q.db.Query(ctx, listExpiredReservations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*TicketReservation{}
	for rows.Next() {
		var i TicketReservation
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.UserID,
			&i.ReservedAt,
			&i.ExpiresAt,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
