// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ticket_types.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getTicketType = `-- name: GetTicketType :one
SELECT id, event_id, nome, price, total_quantity, available_quantity FROM ticket_types
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTicketType(ctx context.Context, id uuid.UUID) (*TicketType, error) {
	row := q.db.QueryRow(ctx, getTicketType, id)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Nome,
		&i.Price,
		&i.TotalQuantity,
		&i.AvailableQuantity,
	)
	return &i, err
}

const getTicketTypeForUpdate = `-- name: GetTicketTypeForUpdate :one
SELECT id, event_id, nome, price, total_quantity, available_quantity FROM ticket_types
WHERE id = $1
LIMIT 1
FOR UPDATE
`

// Trava o lote para atualizar a quantidade disponível com segurança financeira
func (q *Queries) GetTicketTypeForUpdate(ctx context.Context, id uuid.UUID) (*TicketType, error) {
	row := q.db.QueryRow(ctx, getTicketTypeForUpdate, id)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Nome,
		&i.Price,
		&i.TotalQuantity,
		&i.AvailableQuantity,
	)
	return &i, err
}

const listTicketTypesByEvent = `-- name: ListTicketTypesByEvent :many
SELECT id, event_id, nome, price, total_quantity, available_quantity FROM ticket_types
WHERE event_id = $1
ORDER BY price ASC
`

// Lista todos os setores/lotes de um evento para mostrar na página de vendas
func (q *Queries) ListTicketTypesByEvent(ctx context.Context, eventID uuid.UUID) ([]*TicketType, error) {
	rows, err := q.db.Query(ctx, listTicketTypesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*TicketType{}
	for rows.Next() {
		var i TicketType
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Nome,
			&i.Price,
			&i.TotalQuantity,
			&i.AvailableQuantity,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseTicketsStock = `-- name: ReleaseTicketsStock :exec
UPDATE ticket_types
SET available_quantity = available_quantity + $1
WHERE id = $2
`

// Devolve os ingressos ao estoque caso a reserva expire ou seja cancelada
func (q *Queries) ReleaseTicketsStock(ctx context.Context, availableQuantity int32, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, releaseTicketsStock, availableQuantity, iD)
	return err
}

const reserveTicketsStock = `-- name: ReserveTicketsStock :exec
UPDATE ticket_types
SET available_quantity = available_quantity - $1
WHERE id = $2 AND available_quantity >= $1
`

// Deduz a quantidade disponível quando uma reserva é criada
func (q *Queries) ReserveTicketsStock(ctx context.Context, availableQuantity int32, iD uuid.UUID) error {
	_, err := q.db.Exec(ctx, reserveTicketsStock, availableQuantity, iD)
	return err
}

const updateTicketTypePrice = `-- name: UpdateTicketTypePrice :one
UPDATE ticket_types
SET price = $1
WHERE id = $2
RETURNING id, event_id, nome, price, total_quantity, available_quantity
`

// Caso precise virar o lote ou alterar o valor (o preço vira string no Go)
func (q *Queries) UpdateTicketTypePrice(ctx context.Context, price string, iD uuid.UUID) (*TicketType, error) {
	row := q.db.QueryRow(ctx, updateTicketTypePrice, price, iD)
	var i TicketType
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Nome,
		&i.Price,
		&i.TotalQuantity,
		&i.AvailableQuantity,
	)
	return &i, err
}
